server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

logging:
  file: /logs/logs.log
  level:
    root: info
    org.mybatis: info
    org.springframework: info
    org.springframework.jdbc: info
    com.module: info

spring:
  profiles:
      active: dev
  servlet:
    multipart:
      #设置单个文件上传的大小
      max-file-size: 200MB
      #设置上传文件的容量
      max-request-size: 200MB

mybatis:
  typeAliasesPackage: com.module.merchant.domain
  mapper-locations: classpath:/config/mybatis/*/*Mapper.xml