server:
  port: 8090
  servlet:
    context-path: /
debug: false


logging:
  file: /logs/logs.log
  level:
    root: info
    org.mybatis: info
    org.springframework: info
    org.springframework.jdbc: info
    com.module: info
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/